spring:
  application:
    name: feedbacks

#  datasource:
#    url: "jdbc:postgresql://localhost/workout_bot"
#    username: workout_bot
#    password: workout_bot

#  flyway:
#    enabled: true

telegram:
  name: WildberriesFeedbacksBot
  token: 6763583729:AAHtW2WTReZmanAMcYAiDts9DxzkG3vyp50
#  uri: https://158.160.17.180:8081/
  uri: https://84.201.136.77

server:
  ssl:
    enabled: false
  port: 8080